export function buildScienceJudgePrompt(brief, plan) {
  const guardrails = Array.isArray(plan?.accuracy_guardrails) ? plan.accuracy_guardrails : [];
  const exclusions = Array.isArray(plan?.exclusions) ? plan.exclusions : [];
  return [
    "You are HAL Science Director's independent visual science reviewer.",
    "Evaluate only the supplied media artifact. Do not trust the plan merely because it was generated by another model.",
    "Return ONLY compact valid JSON with this exact shape: {\"score\":number,\"verdict\":\"pass|revise\",\"feedback\":string,\"visible_issues\":[string],\"suggested_correction\":string}.",
    "Score from 1 to 10. Use pass only for score 7 or higher.",
    "Look specifically for impossible geometry, wrong scale relationships, invented labels or measurements, misleading causal depiction, impossible lighting/shadows, duplicated anatomy/objects, and visual metaphors that could be mistaken for literal science.",
    "Base every criticism on what is visibly present in the artifact. Keep visible_issues to at most 4 concise items.",
    `Scientific concept: ${brief.concept}`,
    ...(brief.accuracyNotes ? [`Operator accuracy constraints: ${brief.accuracyNotes}`] : []),
    ...(plan?.observable_claim ? [`Planned observable claim: ${plan.observable_claim}`] : []),
    ...(guardrails.length ? [`Planner guardrails: ${guardrails.join(" | ")}`] : []),
    ...(exclusions.length ? [`Must avoid: ${exclusions.join(" | ")}`] : [])
  ].join("\n");
}

export function parseScienceJudgeJson(value) {
  const source = decodeTransportEscapes(String(value || "").trim());
  const fenced = source.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1] || source;
  const start = fenced.indexOf("{");
  const end = fenced.lastIndexOf("}");
  if (start < 0 || end <= start) throw new Error("Science judge did not return JSON.");
  const parsed = JSON.parse(fenced.slice(start, end + 1));
  const score = Math.max(1, Math.min(10, Math.round(Number(parsed.score))));
  if (!Number.isFinite(score)) throw new Error("Science judge returned an invalid score.");
  const feedback = clean(parsed.feedback, 700);
  if (!feedback) throw new Error("Science judge returned empty feedback.");
  const visibleIssues = Array.isArray(parsed.visible_issues)
    ? parsed.visible_issues.map((item) => clean(item, 350)).filter(Boolean).slice(0, 4)
    : [];
  const suggestedCorrection = clean(parsed.suggested_correction, 1000) || feedback;
  return {
    score,
    verdict: score >= 7 ? "pass" : "revise",
    feedback,
    visibleIssues,
    suggestedCorrection
  };
}

export async function judgeScienceArtifact({ livepeer, outputUrl, brief, plan, capability = "gemini-text" }) {
  const payload = await livepeer.runCapability({
    capability,
    prompt: buildScienceJudgePrompt(brief, plan),
    sourceUrl: outputUrl,
    timeout: 90,
    async: false,
    idempotencyKey: `hal_judge_${stableKey(outputUrl, brief.concept)}`
  });
  const text = payload?.result?.content?.map((item) => item?.text).filter(Boolean).join("\n") || "";
  return parseScienceJudgeJson(text);
}

function stableKey(...parts) {
  let hash = 2166136261;
  for (const ch of parts.join(":")) {
    hash ^= ch.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(16);
}

function decodeTransportEscapes(value) {
  let source = String(value || "").trim();
  if (source.includes('\\\"') && /\\\\[nrt]/.test(source)) {
    source = source
      .replace(/\\\\r\\\\n/g, "\n")
      .replace(/\\\\n/g, "\n")
      .replace(/\\\\r/g, "\n")
      .replace(/\\\\t/g, "\t")
      .replace(/\\\\\"/g, '"')
      .replace(/\\\\\\\\/g, "\\");
  }
  if (source.startsWith('"') && source.endsWith('"')) {
    try {
      const decoded = JSON.parse(source);
      if (typeof decoded === "string") source = decoded.trim();
    } catch {}
  }
  return source;
}

function clean(value, max) {
  return String(value ?? "").replace(/[\u0000-\u001f]+/g, " ").replace(/\s+/g, " ").trim().slice(0, max);
}
